// packages/Phoria.Web/ui/src/app/components/Counter/Counter.svelte
<script lang="ts">
// biome-ignore lint/style/useConst: svelte
let count = 0
</script>

<div class="svelte-counter">
	<a href="https://svelte.dev" target="_blank" rel="noreferrer">
		<img src="/svelte.svg" class="logo svelte" alt="Svelte Logo" />
	</a>
	<button type="button" on:click={() => count++}>count is { count }</button>
	<p>
		Edit
		<code>ui/app/components/Counter/Counter.svelte</code> to test HMR
	</p>
</div>

<style>
.logo.svelte:hover {
	filter: drop-shadow(0 0 2em #ff3e00aa);
}

button {
	display: block;
	margin: auto;
}
</style>

// packages/Phoria.Web/ui/src/app/components/Counter/Counter.vue
<script setup lang="ts">
import { ref } from "vue"

const props = defineProps<{ startAt?: number }>()

const count = ref(props.startAt ?? 0)
</script>

<template>
	<div class="vue-counter">
		<a href="https://vuejs.org/" target="_blank" rel="noreferrer">
			<img src="/vue.svg" class="logo vue" alt="Vue logo" />
		</a>
		<button type="button" @click="count++">count is {{ count }}</button>
		<p>
			Edit
			<code>ui/app/components/Counter/Counter.vue</code> to test HMR
		</p>
	</div>
</template>

<style scoped>
.logo.vue:hover {
	filter: drop-shadow(0 0 2em #42b883aa);
}

button {
	display: block;
	margin: auto;
}
</style>
