// packages/Phoria.Web/ui/src/app/components/Counter/Counter.tsx
import { useState } from "react"
import reactLogo from "/react.svg"
import css from "./Counter.module.css"

interface CounterProps {
	startAt?: number
}

function Counter({ startAt }: CounterProps) {
	const [count, setCount] = useState(startAt ?? 0)

	return (
		<div className={`react-counter ${css.counter}`}>
			<a href="https://react.dev" target="_blank" rel="noreferrer">
				<img src={reactLogo} className="logo react" alt="React logo" />
			</a>
			<button type="button" onClick={() => setCount((count) => count + 1)}>
				count is {count}
			</button>
			<p>
				Edit <code>ui/app/components/Counter/Counter.tsx</code> to test HMR
			</p>
		</div>
	)
}

export { Counter }

export const componentPath = import.meta.url

// packages/Phoria.Web/ui/src/app/components/Counter/Counter.vue
<script setup lang="ts">
import { ref } from "vue"

const props = defineProps<{ startAt?: number }>()

const count = ref(props.startAt ?? 0)
</script>

<script module lang="ts">
	export const componentPath = import.meta.url
</script>

<template>
	<div class="vue-counter">
		<a href="https://vuejs.org/" target="_blank" rel="noreferrer">
			<img src="/vue.svg" class="logo vue" alt="Vue logo" />
		</a>
		<button type="button" @click="count++">count is {{ count }}</button>
		<p>
			Edit
			<code>ui/app/components/Counter/Counter.vue</code> to test HMR
		</p>
	</div>
</template>

<style scoped>
.logo.vue:hover {
	filter: drop-shadow(0 0 2em #42b883aa);
}

button {
	display: block;
	margin: auto;
}
</style>
